name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # TODO [ubuntu-latest, windows-latest, macos-latest] https://github.com/php-actions/composer/issues/95
        # https://endoflife.date/php
        php-version: ['8.1', '8.2', '8.3']

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-version }}
      - name: Lint with Psalm
        run: ./vendor/bin/psalm --shepherd --stats --threads=4
      - name: Test with Coverage
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          version: 9 # supports PHP 8.0+
          php_version: ${{ matrix.php-version }}
          php_extensions: xdebug
          args: test --coverage-clover ./coverage.xml
      - name: Upload coverage to Codecov
        if: ${{ matrix.php-version == '8.3' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v3
